YarisTakip/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YarisTakip.Interfaces;
using CloudinaryDotNet.Actions;
using YarisTakip.Models;
using YarisTakip.Services;
using YarisTakip.ViewModel;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Net;

namespace YarisTakip.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IYarisRepository _yarisRespository;
        private readonly IKullaniciRepository _kullaniciRepository;
        private readonly IResimService _resimService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AdminController(IYarisRepository yarisRespository, IKullaniciRepository kullaniciRepository, IHttpContextAccessor httpContextAccessor, IResimService resimService)
        {
            _yarisRespository = yarisRespository;
            _kullaniciRepository = kullaniciRepository;
            _httpContextAccessor = httpContextAccessor;
            _resimService= resimService;
        }

        public async Task<IActionResult> Yarislar()
        {
            IEnumerable<Yaris> yarislar = await _yarisRespository.GetAll();
            return View(yarislar);
        }
        public async Task<IActionResult> Kullanicilar()
        {
            var kullanici = await _kullaniciRepository.GetAllUsers();
            List<KullaniciViewModel> result = new List<KullaniciViewModel>();
            foreach (var user in kullanici)
            {
                var kullaniciViewModel = new KullaniciViewModel()
                {
                    Id = user.Id,
                    KullaniciAdi = user.UserName,
                    KosuHizi = user.KosuHizi,
                    Mesafe = user.Mesafe,
                };
                result.Add(kullaniciViewModel);
            }
            return View(result);
        }

        public  ActionResult KullaniciSil(string id)
        {
            var baseAddress = new Uri("https://localhost");
            var cookieContainer = new CookieContainer();
            using (var handler = new HttpClientHandler() { CookieContainer = cookieContainer })
            using (var client=new HttpClient(handler))
            {
                client.BaseAddress = new Uri("https://localhost:7119/api/");
                cookieContainer.Add(baseAddress, new Cookie(".AspNetCore.Identity.Application", Request.Cookies[".AspNetCore.Identity.Application"]));
                var deleteTask = client.DeleteAsync("Kullanici/" + id);
                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                    return RedirectToAction("Kullanicilar");
            }
            return RedirectToAction("Kullanicilar");
        }

    }
}

YarisTakip/Controllers/HesapController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using YarisTakip.Data;
using YarisTakip.Models;
using YarisTakip.ViewModel;

namespace YarisTakip.Controllers
{
    public class HesapController : Controller
    {
        private readonly UserManager<Kullanici> _kullaniciManager;
        private readonly SignInManager<Kullanici> _signInManager;
        private readonly AppDbContext _context;
        public HesapController(UserManager<Kullanici> userManager, SignInManager<Kullanici> signInManager, AppDbContext context)
        {
            _context = context;
            _signInManager = signInManager;
            _kullaniciManager = userManager;
        }

        public IActionResult Giris()
        {
            var response = new GirisViewModel();
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Giris(GirisViewModel girisViewModel)
        {
            if (!ModelState.IsValid) return View(girisViewModel);

            var kullanici = await _kullaniciManager.FindByEmailAsync(girisViewModel.EmailAdres);

            if (kullanici != null)
            {
                var sifreOnayı = await _kullaniciManager.CheckPasswordAsync(kullanici, girisViewModel.Sifre);
                if (sifreOnayı)
                {
                    var result = await _signInManager.PasswordSignInAsync(kullanici, girisViewModel.Sifre, false, false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Yaris");
                    }
                }
                TempData["Error"] = "Lütfen Tekrar Deneyiniz";
                return View(girisViewModel);
            }
            TempData["Error"] = "Böyle bir kullanıcı yok";
            return View(girisViewModel);
        }

        public IActionResult Kayit()
        {
            var response = new KayitViewModel();
            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Kayit(KayitViewModel kayitViewModel)
        {
            if (!ModelState.IsValid) return View(kayitViewModel);

            var kullanici = await _kullaniciManager.FindByEmailAsync(kayitViewModel.EmailAdres);
            if (kullanici != null)
            {
                TempData["Error"] = "Bu email kullanılmaktadır";
                return View(kayitViewModel);
            }

            var yeniKullanici = new Kullanici()
            {
                Email = kayitViewModel.EmailAdres,
                UserName = kayitViewModel.EmailAdres
            };
            var yenikullaniciResponse = await _kullaniciManager.CreateAsync(yeniKullanici, kayitViewModel.Sifre);

            if (yenikullaniciResponse.Succeeded)
                await _kullaniciManager.AddToRoleAsync(yeniKullanici, KullaniciRolleri.Kullanici);

            return RedirectToAction("Index", "Yaris");
        }

        [HttpPost]
        public async Task<IActionResult> Cikis()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Yaris");
        }
    }
}

YarisTakip/Controllers/KullaniciController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using YarisTakip.Interfaces;
using YarisTakip.Models;
using YarisTakip.Services;
using YarisTakip.ViewModel;

namespace YarisTakip.Controllers
{
    [Authorize]
    public class KullaniciController : Controller
    {
        private readonly IKullaniciRepository _kullaniciRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IResimService _resimService;

        public KullaniciController(IKullaniciRepository kullaniciRepository, IHttpContextAccessor httpContextAccessor, IResimService resimService)
        {
            _kullaniciRepository = kullaniciRepository;
            _httpContextAccessor = httpContextAccessor;
            _resimService = resimService;
        }

        public async Task<IActionResult> Profil(string id)
        {
            var kullaniciId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (kullaniciId != id)
            {
                return RedirectToAction("Giris", "Hesap");
            }
            var kullanici = await _kullaniciRepository.GetUserById(id);
            var kullaniciDetayViewModel = new KullaniciDetayViewModel()
            {
                Id = kullanici.Id,
                KullaniciAdi = kullanici.UserName,
                KosuHizi = kullanici.KosuHizi,
                Mesafe = kullanici.Mesafe,
                ProfilResimURL = kullanici.ProfilResimUrl
            };
            return View(kullaniciDetayViewModel);
        }

        private void MapUserEdit(Kullanici kullanici, EditKullaniciViewModel editVM, ImageUploadResult photoResult)
        {
            kullanici.Id = editVM.Id;
            kullanici.KosuHizi = editVM.KosuHizi;
            kullanici.Mesafe = editVM.Mesafe;
            kullanici.ProfilResimUrl = photoResult.Url.ToString();
        }

        public async Task<IActionResult> EditKullanici(string id)
        {
            var kullaniciId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (kullaniciId != id)
            {
                return RedirectToAction("Giris", "Hesap");
            }
            var kullanici = await _kullaniciRepository.GetUserById(kullaniciId);
            if (kullanici == null) return View("Error");
            var editUserViewModel = new EditKullaniciViewModel()
            {
                Id = kullaniciId,
                KosuHizi = kullanici.KosuHizi,
                Mesafe = kullanici.Mesafe,
                ProfilResimURL = kullanici.ProfilResimUrl
            };
            return View(editUserViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> EditKullanici(EditKullaniciViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("EditKullanici", editVM);
            }

            Kullanici kullanici = await _kullaniciRepository.GetUserById(editVM.Id);

            if (kullanici.ProfilResimUrl == "" || kullanici.ProfilResimUrl == null)
            {

                var photoResult = await _resimService.AddPhotoAsync(editVM.Resim);

                MapUserEdit(kullanici, editVM, photoResult);

                _kullaniciRepository.Update(kullanici);

                return RedirectToAction("Index", "Yaris");
            }
            else
            {
                try
                {
                    await _resimService.DeletePhotoAsync(kullanici.ProfilResimUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(editVM);
                }
                var photoResult = await _resimService.AddPhotoAsync(editVM.Resim);

                MapUserEdit(kullanici, editVM, photoResult);

                _kullaniciRepository.Update(kullanici);

                return RedirectToAction("Index", "Yaris");
            }
        }
    }
}

YarisTakip/Controllers/KullaniciYarisiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using NuGet.Versioning;
using YarisTakip.Data;
using YarisTakip.Interfaces;
using YarisTakip.Models;
using YarisTakip.Repository;

namespace YarisTakip.Controllers
{
    public class KullaniciYarisiController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IKullaniciRepository _kullaniciRepository;
        private readonly IYarisRepository _yarisRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public KullaniciYarisiController(AppDbContext context, IKullaniciRepository kullaniciRepository, IYarisRepository yarisRepository, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _kullaniciRepository = kullaniciRepository;
            _yarisRepository = yarisRepository;
            _httpContextAccessor = httpContextAccessor;
        }
        [Authorize]
        public async Task<IActionResult> Index(string id)
        {
            var kullaniciId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if(kullaniciId != id)
            {
                return RedirectToAction("Giris", "Hesap");
            }
            var kullanici = await _kullaniciRepository.GetUserById(id);
            var appDbContext = _context.KullaniciYarisi.Where(k => k.KullaniciId == kullanici.Id).Include(k => k.Kullanici).Include(k => k.Yaris);
            return View(await appDbContext.ToListAsync());
        }

        public IActionResult YarisKatil(int Id)
        {
            var kullaniciId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var kullaniciYaris = new KullaniciYarisi
            {
                KullaniciId = kullaniciId,
                YarisId = Id,
            };
            _context.KullaniciYarisi.Add(kullaniciYaris);
            _context.SaveChanges();
            return RedirectToAction("Index","Yaris");
        }
    }
}

YarisTakip/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;
@using Microsoft.Extensions.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using System.Security.Claims;
@inject IViewLocalizer ViewLocalizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Yarış Takip</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YarisTakip.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Yaris" asp-action="Index">@ViewLocalizer["title"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Kullanici" asp-action="Profil" asp-route-id="@User.FindFirst(ClaimTypes.NameIdentifier).Value">
                                    <button class="btn btn-outline-primary">@ViewLocalizer["button1"]</button>
                                </form>
                            </li>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("kullanici"))
                            {
                                <li class="nav-item">
                                    <form asp-area="" asp-controller="KullaniciYarisi" asp-action="Index" asp-route-id="@User.FindFirst(ClaimTypes.NameIdentifier).Value">
                                        <button class="btn btn-outline-primary">@ViewLocalizer["button2"]</button>
                                    </form>
                                </li>
                            }
                            @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <form asp-area="" asp-controller="Admin" asp-action="Yarislar">
                                        <button class="btn btn-outline-primary">@ViewLocalizer["button3"]</button>
                                    </form>
                                </li>
                            }
                            <li class="nav-item">
                                <form asp-area="" asp-controller="Hesap" asp-action="Cikis">
                                    <button class="btn btn-outline-danger">@ViewLocalizer["button4"]</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Hesap" asp-action="Giris">@ViewLocalizer["button5"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Hesap" asp-action="Kayit">@ViewLocalizer["button6"]</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @ViewLocalizer["aciklama"] <a href="https://github.com/halilkeklik/YarisTakip">Github Link</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>