YarisTakip/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YarisTakip.Interfaces;
using CloudinaryDotNet.Actions;
using YarisTakip.Models;
using YarisTakip.Services;
using YarisTakip.ViewModel;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Net;

namespace YarisTakip.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IYarisRepository _yarisRespository;
        private readonly IKullaniciRepository _kullaniciRepository;
        private readonly IResimService _resimService;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AdminController(IYarisRepository yarisRespository, IKullaniciRepository kullaniciRepository, IHttpContextAccessor httpContextAccessor, IResimService resimService)
        {
            _yarisRespository = yarisRespository;
            _kullaniciRepository = kullaniciRepository;
            _httpContextAccessor = httpContextAccessor;
            _resimService= resimService;
        }

        public async Task<IActionResult> Yarislar()
        {
            IEnumerable<Yaris> yarislar = await _yarisRespository.GetAll();
            return View(yarislar);
        }
        public async Task<IActionResult> Kullanicilar()
        {
            var kullanici = await _kullaniciRepository.GetAllUsers();
            List<KullaniciViewModel> result = new List<KullaniciViewModel>();
            foreach (var user in kullanici)
            {
                var kullaniciViewModel = new KullaniciViewModel()
                {
                    Id = user.Id,
                    KullaniciAdi = user.UserName,
                    KosuHizi = user.KosuHizi,
                    Mesafe = user.Mesafe,
                };
                result.Add(kullaniciViewModel);
            }
            return View(result);
        }

        public  ActionResult KullaniciSil(string id)
        {
            var baseAddress = new Uri("https://localhost");
            var cookieContainer = new CookieContainer();
            using (var handler = new HttpClientHandler() { CookieContainer = cookieContainer })
            using (var client=new HttpClient(handler))
            {
                client.BaseAddress = new Uri("https://localhost:7119/api/");
                cookieContainer.Add(baseAddress, new Cookie(".AspNetCore.Identity.Application", Request.Cookies[".AspNetCore.Identity.Application"]));
                var deleteTask = client.DeleteAsync("Kullanici/" + id);
                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                    return RedirectToAction("Kullanicilar");
            }
            return RedirectToAction("Kullanicilar");
        }

    }
}

YarisTakip/Controllers/YarisController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Data;
using System.Diagnostics;
using System.Net;
using YarisTakip.Data;
using YarisTakip.Interfaces;
using YarisTakip.Models;
using YarisTakip.ViewModel;

namespace YarisTakip.Controllers
{
    public class YarisController : Controller
    {
        private readonly IYarisRepository _yarisRespository;
        private readonly IResimService _resimService;
        private readonly AppDbContext _context;

        public YarisController(IYarisRepository yarisRespository, IResimService resimService, AppDbContext context)
        {
            _yarisRespository = yarisRespository;
            _resimService = resimService;
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Yaris> yarislar = await _yarisRespository.GetAll();
            return View(yarislar);
        }
        public async Task<IActionResult> Detail(int id)
        {
            Yaris yaris = await _yarisRespository.GetByIdAsync(id);
            return View(yaris);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> Create(CreateYarisViewModel yarisVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _resimService.AddPhotoAsync(yarisVM.Resim);

                var yaris = new Yaris
                {
                    Baslik = yarisVM.Baslik,
                    Aciklama = yarisVM.Aciklama,
                    Resim = result.Url.ToString(),
                    Adres = new Adres
                    {
                        Sokak = yarisVM.Adres.Sokak,
                        Sehir = yarisVM.Adres.Sehir,
                        Ulke = yarisVM.Adres.Ulke,
                    }
                };
                _yarisRespository.Add(yaris);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }
            return View(yarisVM);
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var yaris = await _yarisRespository.GetByIdAsync(id);
            if (yaris == null) return View("Error");
            var clubVM = new EditYarisViewModel
            {
                Baslik = yaris.Baslik,
                Aciklama = yaris.Aciklama,
                AdresId = (int)yaris.AdresId,
                Adres = yaris.Adres,
                URL = yaris.Resim,
                YarisKategori = yaris.YarisKategori
            };
            return View(clubVM);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditYarisViewModel yarisVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit race");
                return View("Edit", yarisVM);
            }

            var kullaniciYaris = await _yarisRespository.GetByIdAsyncNoTracking(id);

            if (kullaniciYaris != null)
            {
                try
                {
                    await _resimService.DeletePhotoAsync(kullaniciYaris.Resim);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(yarisVM);
                }
                var photoResult = await _resimService.AddPhotoAsync(yarisVM.Resim);


                var yaris = new Yaris
                {
                    Id = id,
                    Baslik = yarisVM.Baslik,
                    Aciklama = yarisVM.Aciklama,
                    Resim = photoResult.Url.ToString(),
                    AdresId = yarisVM.AdresId,
                    Adres = yarisVM.Adres,
                    YarisKategori = yarisVM.YarisKategori
                };

                _yarisRespository.Update(yaris);

                return RedirectToAction("Index");
            }
            else
            {
                return View(yarisVM);
            }
        }
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int Id)
        {
            var yarisDetails = await _yarisRespository.GetByIdAsync(Id);
            if (yarisDetails == null) return RedirectToAction("Yarislar", "Admin");
            var appContext =  _context.KullaniciYarisi.FirstOrDefault(k => k.YarisId == yarisDetails.Id);
            if (appContext == null)
            {
                _context.Remove(yarisDetails);
                _context.SaveChanges();
                return RedirectToAction("Yarislar", "Admin");
            }
                return RedirectToAction("Yarislar", "Admin");
        }
    }
}

YarisTakip/Views/Admin/Kullanicilar.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;
@using YarisTakip.ViewModel
@using Microsoft.Extensions.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@model List<KullaniciViewModel>
@inject IViewLocalizer ViewLocalizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <form asp-area="" asp-controller="Admin" asp-action="Yarislar">
                        <button class="btn btn-outline-primary">@ViewLocalizer["button1"]</button>
                    </form>
                </li>
                <li class="nav-item">
                    <form asp-area="" asp-controller="Admin" asp-action="Kullanicilar">
                        <button class="btn btn-outline-primary">@ViewLocalizer["button2"]</button>
                    </form>
                </li>
                <li class="nav-item">
                    <form asp-area="" asp-controller="Yaris" asp-action="Create">
                        <button class="btn btn-outline-primary">@ViewLocalizer["button3"]</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>
<body>
<table class="table">
    <thead>
        <tr>
            <th>
                    @ViewLocalizer["tablo1"]
            </th>
            <th>
                    @ViewLocalizer["tablo2"]
            </th>
            <th>
                    @ViewLocalizer["tablo3"]
            </th>
            <th>
                    @ViewLocalizer["tablo4"]
            </th>
        </tr>
    </thead>
    <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                        @Html.DisplayFor(modelItem => item.KullaniciAdi)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.KosuHizi)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.Mesafe)
                </td>
                <td>
                        <a type="btn btn-success" asp-controller="Admin" asp-action="KullaniciSil" asp-route-id="@item.Id"
                       class="btn btn-danger">@ViewLocalizer["button4"]</a>
                </td>
            </tr>
            }
    </tbody>
</table>
</body>
</html>

YarisTakip/Views/Admin/Yarislar.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;
@using Microsoft.Extensions.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@model IEnumerable<Yaris>
@inject IViewLocalizer ViewLocalizer
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <form asp-area="" asp-controller="Admin" asp-action="Yarislar">
                        <button class="btn btn-outline-primary">@ViewLocalizer["button1"]</button>
                    </form>
                </li>
                <li class="nav-item">
                    <form asp-area="" asp-controller="Admin" asp-action="Kullanicilar">
                        <button class="btn btn-outline-primary">@ViewLocalizer["button2"]</button>
                    </form>
                </li>
                <li class="nav-item">
                    <form asp-area="" asp-controller="Yaris" asp-action="Create">
                        <button class="btn btn-outline-primary">@ViewLocalizer["button3"]</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>
<body>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @ViewLocalizer["tablo1"]
                </th>
                <th>
                    @ViewLocalizer["tablo2"]
                </th>
                <th>
                    @ViewLocalizer["tablo3"]
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Baslik)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.YarisKategori)
                    </td>
                    <td>
                        <a type="btn btn-success" asp-controller="Yaris" asp-action="Detail" asp-route-id="@item.Id"
                       class="btn btn-sm btn-outline-secondary">@ViewLocalizer["button5"]</a>
                        <a type="btn btn-success" asp-controller="Yaris" asp-action="Delete" asp-route-id="@item.Id"
                        class="btn btn-danger">@ViewLocalizer["button4"]</a>
                        <a type="btn btn-success" asp-controller="Yaris" asp-action="Edit" asp-route-id="@item.Id"
                       class="btn btn-danger">@ViewLocalizer["button6"]</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>